name: CI
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "README.md"

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.23"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set git to use LF
        if: matrix.os == 'windows-latest'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: --timeout=10m
          skip-cache: true

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ matrix.go }}
          go-package: ./...
          cache: false

      - name: Run tests
        run: |
          git diff --cached --exit-code
          go test ./... -v -cover -coverprofile=cover.out

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: cover.html
